### PR TITLE
Adding GitHub Actions to build/format/lint/test

### PR DESCRIPTION
**Pull request by fosdickio**

### CODE REVIEW

**Comment by nhatcher** [comment]
Can we hold on a bit longer for this?
Let's have a phone call about this. I am not even sure how to do the tests here

**Comment by fosdickio** [comment]
> Can we hold on a bit longer for this? Let's have a phone call about this. I am not even sure how to do the tests here

Sure.  No problem.  It might be worthwhile to build, format, and lint for now while we figure out a testing strategy.

**Comment by nhatcher** [comment]
On second thought, you are right. Merged

**Comment by nhatcher** [comment]
Hmmm, this actually breaks because of the toml config. Ignore this, I will fix it tomorrow morning

**Pull request merged**
